apiVersion: apps/v1
kind: Deployment
metadata:
  name: Swiggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Swiggy-project
  template:
    metadata:
      labels:
        app: Swiggy-project
    spec:
      containers:
        - name: Swiggy-project
          image: srinath7019/swiggy:latest
          ports:
            - containerPort: 3000
