apiVersion: v1
kind: Service
metadata:
  name: swiggy-service
spec:
  selector:
    app: swiggy-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: NodePort   # Change from LoadBalancer to NodePort
